version: "3"

services:
  app:
    build: .
    ports:
      - "8777:5050"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5050