# version: "3"

# services:
#   app:
#     build: .
#     ports:
#       - "5050:5050"
#     volumes:
#       - .:/app
#     environment:
#       FLASK_APP: app.py
#       FLASK_RUN_HOST: 0.0.0.0
#       FLASK_RUN_PORT: 5050


version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build:
      context: ./server
    ports:
      - 5050:5050
